try {
	${4}
} catch (${1:Exception} ${2:e}) {
} finally {
	${3}
}
